---
# GitRepository tells Flux where to fetch the repo from
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: online-inference
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/paxsolutions/online-inference-platform-demo
  ref:
    branch: main
