apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "online-inference.fullname" . }}
  labels: {{- include "online-inference.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "online-inference.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "online-inference.selectorLabels" . | nindent 8 }}
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: REDIS_URL
              value: {{ .Values.env.REDIS_URL | quote }}
            - name: CACHE_TTL_SECONDS
              value: {{ .Values.env.CACHE_TTL_SECONDS | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
