{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.host }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.host }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.host }}
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          args: ["--save", ""]
          ports:
            - containerPort: {{ .Values.redis.port }}
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.host }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: {{ .Values.redis.host }}
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
{{- end }}
