{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "online-inference.fullname" . }}
  labels: {{- include "online-inference.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "online-inference.selectorLabels" . | nindent 6 }}
  strategy:
    canary:
      canaryService: {{ include "online-inference.fullname" . }}-canary
      stableService: {{ include "online-inference.fullname" . }}
      steps:
        {{- toYaml .Values.rollout.steps | nindent 8 }}
      analysis:
        templates:
          - templateName: {{ include "online-inference.fullname" . }}-success-rate
        startingStep: {{ .Values.rollout.analysisStartingStep }}
        args:
          - name: service-name
            value: {{ include "online-inference.fullname" . }}-canary
  template:
    metadata:
      labels: {{- include "online-inference.selectorLabels" . | nindent 8 }}
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: REDIS_URL
              value: {{ .Values.env.REDIS_URL | quote }}
            - name: CACHE_TTL_SECONDS
              value: {{ .Values.env.CACHE_TTL_SECONDS | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.env.OTEL_EXPORTER_OTLP_ENDPOINT | quote }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe: {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe: {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- with .Values.startupProbe }}
          startupProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
