apiVersion: v1
kind: Service
metadata:
  name: {{ include "online-inference.fullname" . }}
  labels:
    {{- include "online-inference.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "online-inference.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
