replicaCount: 1
image:
  repository: ghcr.io/paxsolutions/online-inference-platform-demo/inference-api
  tag: v0.3.1
  pullPolicy: IfNotPresent
imagePullSecrets:
  - name: ghcr-pull-secret
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
env:
  REDIS_URL: redis://redis:6379/0
  CACHE_TTL_SECONDS: "60"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
  QUEUE_NAME: inference:queue
  RESULT_TTL_SECONDS: "600"
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 75
redis:
  enabled: true
  image: redis:7-alpine
  host: redis
  port: 6379
otel:
  endpoint: http://otel-collector:4317
readinessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
livenessProbe:
  httpGet:
    path: /healthz
    port: 8080
  initialDelaySeconds: 90
  periodSeconds: 20
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: /metrics
worker:
  enabled: true
  name: inference-worker
  image:
    repository: ghcr.io/paxsolutions/online-inference-platform-demo/inference-worker
    tag: v0.3.1
    pullPolicy: IfNotPresent
  env:
    REDIS_URL: redis://redis:6379/0
    QUEUE_NAME: inference:queue
    RESULT_TTL_SECONDS: "600"
    OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318/v1/traces
    METRICS_PORT: "9100"
keda:
  enabled: true
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 10
  redis:
    address: redis:6379
    listName: inference:queue
    listLength: "5"
prometheus:
  enabled: true
  scrapeInterval: 5s
  service:
    name: prometheus
    port: 9090
