name: Release

on:
  push:
    tags: ['v*.*.*']

jobs:
  release:
    uses: ./.github/workflows/reusable-release.yml
    with:
      services: '[{"name": "inference-api", "context": "./services/inference-api"}, {"name": "inference-worker", "context": "./services/inference-worker"}]'
      helm-chart-path: charts/online-inference
      image-tag-paths: '[".image.tag", ".worker.image.tag"]'
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
